/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robot_tangwa_discreminateexper_JniTest */

#ifndef _Included_robot_tangwa_discreminateexper_JniTest
#define _Included_robot_tangwa_discreminateexper_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robot_tangwa_discreminateexper_JniTest
 * Method:    hello_jni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_robot_tangwa_discreminateexper_JniTest_hello_1jni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
